# This wor<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Purchasing Order Portal</title>
    <style>
        body {
            margin: 0;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: #F5D10D;
        }

        header {
            background-color: #2c3e50;
            color: white;
            padding: 20px 40px;
            display: flex;
            align-items: center;
        }

        .logo {
            height: 100px;
            margin-right: 4px;
        }

        .portal-title {
            font-size: 30px;
        }

        .container {
            max-width: 1000px;
            margin: 40px auto;
            padding: 20px;
            background-color: white;
            border-radius: 12px;
            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.08);
        }

        .section {
            margin-bottom: 30px;
        }

        h2 {
            color: #2c3e50;
        }

        .button-group a {
            text-decoration: none;
            background-color: #F5D10D;
            color: white;
            padding: 12px 24px;
            margin-right: 15px;
            border-radius: 6px;
            transition: background-color 0.3s ease;
        }

        .button-group a:hover {
            background-color: #F5D10D;
        }

        footer {
            text-align: center;
            padding: 5px;
            font-size: 15px;
            color: #777;
        }
    </style>
</head>
<body>

    <!-- Header with logo and title -->
    <header>
        <img src="file:///C:/Users/Hyacinth%20Mae/Downloads/CODE/download%20(2).png" alt="Logo" class="logo">
        <div class="portal-title">KARPARTS360 PO</div>
    </header>

    <!-- Main Content Area -->
    <div class="container">
        <div class="section">
            <h2>Welcome!</h2>
            <p>This page is your guide to all purchase order related tasks and procedures.
      Explore step-by-step instructions, best practices, and useful resources to
      streamline your workflow and ensure process compliance.</p>
        </div>

        <div class="section button-group">
            <h1><a href="file:///C:/Users/Hyacinth%20Mae/Downloads/CODE/PO%20TASK%20LIST.HTML">📄 PO TASKS AND PROCESSES</a>
           
        </div>
              
            </ul>
        </div>
    </div>

    <!-- Footer -->
    <footer>
        &copy; 2025 Purchasing Order Portal. All rights reserved.
    </footer>

</body>
</html>kflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow lets you generate SLSA provenance file for your project.
# The generation satisfies level 3 for the provenance requirements - see https://slsa.dev/spec/v0.1/requirements
# The project is an initiative of the OpenSSF (openssf.org) and is developed at
# https://github.com/slsa-framework/slsa-github-generator.
# The provenance file can be verified using https://github.com/slsa-framework/slsa-verifier.
# For more information about SLSA and how it improves the supply-chain, visit slsa.dev.

name: SLSA generic generator
on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      digests: ${{ steps.hash.outputs.digests }}

    steps:
      - uses: actions/checkout@v4

      # ========================================================
      #
      # Step 1: Build your artifacts.
      #
      # ========================================================
      - name: Build artifacts
        run: |
            # These are some amazing artifacts.
            echo "artifact1" > artifact1
            echo "artifact2" > artifact2

      # ========================================================
      #
      # Step 2: Add a step to generate the provenance subjects
      #         as shown below. Update the sha256 sum arguments
      #         to include all binaries that you generate
      #         provenance for.
      #
      # ========================================================
      - name: Generate subject for provenance
        id: hash
        run: |
          set -euo pipefail

          # List the artifacts the provenance will refer to.
          files=$(ls artifact*)
          # Generate the subjects (base64 encoded).
          echo "hashes=$(sha256sum $files | base64 -w0)" >> "${GITHUB_OUTPUT}"

  provenance:
    needs: [build]
    permissions:
      actions: read   # To read the workflow path.
      id-token: write # To sign the provenance.
      contents: write # To add assets to a release.
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.4.0
    with:
      base64-subjects: "${{ needs.build.outputs.digests }}"
      upload-assets: true # Optional: Upload to a new release
